{"name": "Авторизация с неверными данными", "status": "passed", "description": "Проверка ошибки при попытке авторизоваться с неверными логином или паролем.", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1729504165880, "stop": 1729504165970}, {"name": "Проверка ошибки 401", "status": "passed", "start": 1729504165970, "stop": 1729504165970}], "parameters": [{"name": "login_data", "value": "{'email': 'test-temp@yandex.ru', 'password': ''}"}], "start": 1729504165880, "stop": 1729504165972, "uuid": "13ac71e3-25d4-45fb-a6d0-d98417c7204a", "historyId": "a9cdb5c787dabbbd8503f03d963bb57b", "testCaseId": "6959df27143f6d36a7879a2443ed36e4", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "29772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}