{"name": "Авторизация с неверными данными", "status": "passed", "description": "Проверка ошибки при попытке авторизоваться с неверными логином или паролем.", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1729504165706, "stop": 1729504165878}, {"name": "Проверка ошибки 401", "status": "passed", "start": 1729504165878, "stop": 1729504165878}], "parameters": [{"name": "login_data", "value": "{'email': '', 'password': 'password'}"}], "start": 1729504165706, "stop": 1729504165878, "uuid": "9cec3f00-6483-4a98-8f1e-f36feb3de49e", "historyId": "67068edef62552bcde904848dc58355b", "testCaseId": "6959df27143f6d36a7879a2443ed36e4", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "29772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}