{"name": "Авторизация с неверными данными", "status": "passed", "description": "Проверка ошибки при попытке авторизоваться с неверными логином или паролем.", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1729504165609, "stop": 1729504165702}, {"name": "Проверка ошибки 401", "status": "passed", "start": 1729504165702, "stop": 1729504165702}], "parameters": [{"name": "login_data", "value": "{'email': 'test-temp@yandex.ru', 'password': 'wrongpassword'}"}], "start": 1729504165609, "stop": 1729504165703, "uuid": "e79215a9-04ed-4a8e-89a9-23f2ae1ae48e", "historyId": "add69eca9c6399cbf7c6155a226c3b9c", "testCaseId": "6959df27143f6d36a7879a2443ed36e4", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "29772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}