{"name": "Авторизация с неверными данными", "status": "passed", "description": "Проверка ошибки при попытке авторизоваться с неверными логином или паролем.", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1729504165510, "stop": 1729504165607}, {"name": "Проверка ошибки 401", "status": "passed", "start": 1729504165607, "stop": 1729504165607}], "parameters": [{"name": "login_data", "value": "{'email': 'wrong-email@yandex.ru', 'password': 'password'}"}], "start": 1729504165510, "stop": 1729504165607, "uuid": "c7c9d9ea-33b2-4813-87f1-fd6bbac22dfe", "historyId": "f774dc7755c4fcd5217c4ceb17e94522", "testCaseId": "6959df27143f6d36a7879a2443ed36e4", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "29772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}